# This file was generated by GoReleaser. DO NOT EDIT.
cask "olivares" do
  version "26.8.0"

  on_macos do
    on_intel do
      sha256 "e2b55f9048c4effa6c71f002e073f1c7dadfbc728627d2eccb9784545179afa5"
      url "https://github.com/olivaresai/olivares/releases/download/v#{version}/olivares_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4572f4c8edf54d4df2ee6779116be8dfd7649aabcff25a2cb8fba1b0729d1924"
      url "https://github.com/olivaresai/olivares/releases/download/v#{version}/olivares_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0625f5af9fba4ba6d7edfabb0eb6a67293f7214e3e0ef3b7d65d5cef804dd331"
      url "https://github.com/olivaresai/olivares/releases/download/v#{version}/olivares_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f1cad0bbed85ea66a4f66f702778052b2045a83b3c0371e93ce62812c8c13aa"
      url "https://github.com/olivaresai/olivares/releases/download/v#{version}/olivares_#{version}_linux_arm64.tar.gz"
    end
  end

  name "olivares"
  desc "Ground truth for enterprise AI — self-hosted AI governance control plane"
  homepage "https://olivares.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "olivares"

  # No zap stanza required

  caveats <<~EOS
    Loopback-only by default; the engine prints a first-boot setup token. Verify any
    release with scripts/verify-release.sh in the source repository.
  EOS
end
