# This file was generated by GoReleaser. DO NOT EDIT.
cask "olivares" do
  version "26.9.0"

  on_macos do
    on_intel do
      sha256 "eb4e5586b617639056d3b21aba7f7c725b61e66c59cd3ad75c2893aec79b57d9"
      url "https://github.com/olivaresai/olivares/releases/download/v#{version}/olivares_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "161000135f59e28a4132cd2254dad45f6ce88a47c9607c3fbdefe3bad8e3b788"
      url "https://github.com/olivaresai/olivares/releases/download/v#{version}/olivares_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9246de50ab22a1a02c7f56b2ec5c360c16f1266528be03867f582efdadf735f2"
      url "https://github.com/olivaresai/olivares/releases/download/v#{version}/olivares_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "481959b87926603b0e5974bfea53d77e05a35e950bc6a452e6612fc886429260"
      url "https://github.com/olivaresai/olivares/releases/download/v#{version}/olivares_#{version}_linux_arm64.tar.gz"
    end
  end

  name "olivares"
  desc "Ground truth for enterprise AI — self-hosted AI governance control plane"
  homepage "https://olivares.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "olivares"

  # No zap stanza required

  caveats <<~EOS
    Loopback-only by default; the engine prints a first-boot setup token. Verify any
    release with scripts/verify-release.sh in the source repository.
  EOS
end
