# This file was generated by GoReleaser. DO NOT EDIT.
cask "olivares" do
  version "26.8.0"

  on_macos do
    on_intel do
      sha256 "f44163d3f83f05b6bdcae6ebbd0c10808e7b47b5ac3f034a73af19495d0b52a9"
      url "https://github.com/olivaresai/olivares/releases/download/v#{version}/olivares_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b2b728a1c01d6d25a123e031eb67dd7b2f3819bb9befbe2eeb74a2102da5429"
      url "https://github.com/olivaresai/olivares/releases/download/v#{version}/olivares_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "235df2e55f48560df7724b652bb1ca9d4e1cec7574b0cbb7bff33a9d0467615a"
      url "https://github.com/olivaresai/olivares/releases/download/v#{version}/olivares_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1806356ef9320c34f2c4694fc8cc71dc545a1a71d45296a3846533d9514115b3"
      url "https://github.com/olivaresai/olivares/releases/download/v#{version}/olivares_#{version}_linux_arm64.tar.gz"
    end
  end

  name "olivares"
  desc "Ground truth for enterprise AI — self-hosted AI governance control plane"
  homepage "https://olivares.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "olivares"

  # No zap stanza required

  caveats <<~EOS
    Loopback-only by default; the engine prints a first-boot setup token. Verify any
    release with scripts/verify-release.sh in the source repository.
  EOS
end
